# Generated by Django 3.1.5 on 2021-04-08 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedby',
            field=models.ManyToManyField(default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
