# Generated by Django 3.1.5 on 2021-02-11 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=25)),
                ('starting_bid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('image', models.URLField(default='None')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.auctionlisting')),
                ('user', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bid_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('listing', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.auctionlisting')),
                ('user', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
