# Generated by Django 3.1.5 on 2021-02-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='user',
        ),
    ]
