# Generated by Django 3.1.5 on 2021-02-09 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210208_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='listing_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
