# Generated by Django 3.1.5 on 2021-02-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_listings', to='auctions.auctionlisting'),
        ),
    ]
