# Generated by Django 3.1.5 on 2021-02-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='listing_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='auctions.auctionlisting'),
        ),
    ]
