# Generated by Django 3.1.5 on 2021-02-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210209_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
