# Generated by Django 3.1.5 on 2021-02-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210209_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(upload_to='auctions/uploads/'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_title',
            field=models.CharField(max_length=100),
        ),
    ]
