# Generated by Django 3.1.5 on 2021-02-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210212_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
