# Generated by Django 3.1.5 on 2021-02-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210212_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='url',
            field=models.URLField(),
        ),
    ]
