# Generated by Django 3.1.5 on 2021-02-11 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210210_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bid_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.auctionlisting')),
            ],
        ),
    ]
