# Generated by Django 3.1.5 on 2021-03-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_user_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Followers',
            new_name='UserFollowers',
        ),
    ]
