# Generated by Django 3.1.5 on 2021-03-20 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210317_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
