# Generated by Django 3.1.5 on 2021-03-25 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210323_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
