# Generated by Django 3.1.5 on 2021-03-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210325_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowers',
            new_name='Following',
        ),
    ]
